### ISSUE TITLE
Use `unknown` as the default any type rather than literal `{}`

### ISSUE THREAD

**Issue by chrisui** [Code-Hex/graphql-codegen-typescript-validation-schema#17] opened 2022-02-10 18:28 UTC
## Context

Referencing the following code:

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/8105f2b51dd62241f6daae8abc97675374fae5b7/src/zod/index.ts#L36

Currently, with a custom scalar `Date: Date` (see graphql-codegen `scalarMap` config) we end up with type errors such as `"{} is missing properties from Date toLocaleString, ..."` etc.

## Proposal

Replace `{}` with `unknown` would allow consumers of this library to cast as neccessary.

**Comment by wiksien** [comment] 2022-02-11 01:54
I will fix that.

**Comment by Code-Hex** [comment] 2022-02-11 02:57
@chrisui Thanks for your reporting!
This plugin has been developing under the assumption that it inherited the settings of the typescript plugin. for example

```yaml
example/zod/schemas.ts:
    plugins:
      - ./dist/main/index.js:
          schema: zod
          scalars:
            Date: Date
```

It was supposed to create a schema that takes into account the Date object. This is a bug and will be fixed.

**Comment by Code-Hex** [comment] 2022-02-11 03:43
@chrisui Could you be more specific?
What kind of code are you trying to write that will cause the problem you are suggesting? Thanks.

**Comment by wiksien** [comment] 2022-02-11 03:52
@Code-Hex Just so I undestand correctly, I am supposed to import the Date value from ./dist/main/index.js and use it in DeclarationBlock? If the Date value is empty use unknown right? Is it possible for it to be empty?

**Comment by Code-Hex** [comment] 2022-02-11 04:59
@wiksien Thanks.

I think the Date object is just example. The actual problem is "{} cannot convert to object" (maybe)

I didn't understand enough what he want actually. Maybe 2 candidates.

1. If @chrisui want to use Date object simply, we have to generate `z.date()` instead of `definedNonNullAnySchema`
2. The problem is "{} cannot convert to object they wanted" then we have to consider to use `z.unknown`

I don't understand what do you mean "empty"? You said "optional or null" right?

> Is it possible for it to be empty?

**Comment by wiksien** [comment] 2022-02-11 05:40
@Code-Hex Yeah I meant null, sorry my bad, thought shortcut.

**Comment by Code-Hex** [comment] 2022-02-11 06:54
@wiksien I see. If GraphQL schema like below and scalar `Date` as typed `unknown` will be generated types as nullable or optional

```gql
input Day {
  date: Date
}
```

then

```ts
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Scalars = {
  ID: string;
  String: string;
  ... // some scalars
  Date: unknown;
};

export type Day = {
  date?: InputMaybe<Scalars['Date']>; // unknown | null | undefined
};
```

And also if it is required in GraphQL schema then generated like below.

```ts
export type Day = {
  date: Scalars['Date']; // unknown
};
```

I answer your questions

No, This project is used only typescript.

>  I am supposed to import the Date value from ./dist/main/index.js and use it in DeclarationBlock?

Yes, you can use `z.unknown()`. but if required, I think you can not use `z.unknown()` (https://github.com/colinhacks/zod/issues/884)

> If the Date value is empty use unknown right?

I think there is no method (but if you have a good code to suggest, please let me know.)
> Is it possible for it to be empty?

**Comment by chrisui** [comment] 2022-02-11 14:07
Hey, sorry for delay in reply.

I am passing `scalars` like:

`
`

**Comment by chrisui** [comment] 2022-02-11 14:21
Is there a equivalent to `zodSchemasMap`?

https://github.com/withshepherd/graphql-codegen-zod#configs

**Comment by Code-Hex** [comment] 2022-02-11 15:31
@chrisui Thanks for more details!

I got it. If it's really a problem, we should consider addressing the second.

> 2. The problem is "{} cannot convert to object they wanted" then we have to consider to use z.unknown (too difficult)

However, your use-case seems to work fine also using the `definedNonNullAny` type.

https://codesandbox.io/s/zod-example-forked-090ld?file=/src/index.ts:0-956

If there are any mistakes, please point me out.

**Closed** 2022-02-14 14:06 UTC
Labels: good first issue

**Comment by Code-Hex** [comment] 2022-02-16 15:23
@chrisui I hope this change would help you
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/18
